defaults: &defaults
  root_ids: <%= ENV['SETTING_ROOT_IDS'] || [] %>
  root_as_ids: []

  wechat:
    component:
      appid: <%= ENV['SETTING_WECHAT_COMPONENT_APPID'] %>
      appsecret: <%= ENV['SETTING_WECHAT_COMPONENT_APPSECRET'] %>
      encoding_aes_key: <%= ENV['SETTING_WECHAT_COMPONENT_ENCODING_AES_YEY'] %>
      authorization_callback_url: <%= ENV['SETTING_WECHAT_COMPONENT_AUTHORIZATION_CALLBACK_URL'] %>
      token: <%= ENV['SETTING_WECHAT_COMPONENT_TOKEN'] %>

  qiniu:
    bucket: <%= ENV['SETTING_QINIU_BUCKET'] %>
    domain: <%= ENV['SETTING_QINIU_DOMAIN'] %>
    access_key: <%= ENV['SETTING_QINIU_ACCESS_KEY'] %>
    secret_key: <%= ENV['SETTING_QINIU_SECRET_KEY'] %>
    styles:
      main: imageView/2/w/360/q/85
      cover: imageMogr2/thumbnail/!640x320r/gravity/Center/crop/640x320
      logo: imageView2/1/w/132/h/132/q/85
      welcome: imageMogr2/thumbnail/!360x200r/gravity/Center/crop/360x200
      small_welcome: imageMogr2/thumbnail/!50x50r/gravity/Center/crop/50x50
    attachment:
      bucket: <%= ENV['SETTING_QINIU_ATTACHMENT_BUCKET'] %>
      domain: <%= ENV['SETTING_QINIU_ATTACHMENT_DOMAIN'] %>
      size: <%= ENV['SETTING_QINIU_ATTACHMENT_SIZE'] %>
    exportable_file:
      bucket: <%= ENV['SETTING_QINIU_EXPORTABLE_FILE_BUCKET'] %>
      domain: <%= ENV['SETTING_QINIU_EXPORTABLE_FILE_DOMAIN'] %>
    material:
      image:
        bucket: <%= ENV['SETTING_QINIU_MATERIAL_IMAGE_BUCKET'] %>
        domain: <%= ENV['SETTING_QINIU_MATERIAL_IMAGE_DOMAIN'] %>
        size: <%= ENV['SETTING_QINIU_MATERIAL_IMAGE_SIZE'] %>

  yunpian:
    api_key: <%= ENV['SETTING_YUNPIAN_API_KEY'] %>
    tpl_id: <%= ENV['SETTING_YUNPIAN_TPL_ID'] %>
    involved_tpl_id: <%= ENV['SETTING_YUNPIAN_INVOLVED_TPL_ID'] %>
    tpl_id_with_short_url: <%= ENV['SETTING_YUNPIAN_TPL_ID_WITH_SHORT_URL'] %>
    verify_code_tpl_id: <%= ENV['SETTING_YUNPIAN_VERIFY_CODE_TPL_ID'] %>
    subscription:
      comment_tpl_id: <%= ENV['SETTING_YUNPIAN_SUBSCRIPTION_COMMENT_TPL_ID'] %>
      response_created_tpl_id: <%= ENV['SETTING_YUNPIAN_SUBSCRIPTION_RESPONSE_CREATED_TPL_ID'] %>
      response_updated_tpl_id: <%= ENV['SETTING_YUNPIAN_SUBSCRIPTION_RESPONSE_UPDATED_TPL_ID'] %>
      response_tpl_id: <%= ENV['SETTING_YUNPIAN_SUBSCRIPTION_RESPONSE_TPL_ID'] %>
      organization_application_tpl_id: <%= ENV['SETTING_YUNPIAN_SUBSCRIPTION_ORGANIZATION_APPLICATION_TPL_ID'] %>
      bunch_tpl_id: <%= ENV['SETTING_YUNPIAN_SUBSCRIPTION_BUNCH_TPL_ID'] %>

  slack_notifier:
    webhook_url: <%= ENV['SETTING_SLACK_NOTIFIER_WEBHOOK_URL'] %>
    channel: <%= ENV['SETTING_SLACK_NOTIFIER_CHANNEL'] %>
    username: <%= ENV['SETTING_SLACK_NOTIFIER_USERNAME'] %>

  response:
    async_import_min: <%= ENV['SETTING_RESPONSE_ASYNC_IMPORT_MIN'] %>
    async_export_min: <%= ENV['SETTING_RESPONSE_ASYNC_EXPORT_MIN'] %>
    file_expired_minutes: <%= ENV['SETTING_RESPONSE_FILE_EXPIRED_MINUTES'] %>

  member:
    async_import_min: <%= ENV['SETTING_MEMBER_ASYNC_IMPORT_MIN'] %>

  attachments:
    download_expired_minutes: <%= ENV['SETTING_ATTACHMENTS_DOWNLOAD_EXPIRED_MINUTES'] %>

  app:
    domain: <%= ENV['SETTING_APP_DOMAIN'] %>
    ip: <%= ENV['SETTING_APP_IP'] %>
    cms_cache_expired_hours: <%= ENV['SETTING_APP_CMS_CACHE_EXPIRED_HOURS'] %>
    default_site_name: <%= ENV['SETTING_APP_DEFAULT_SITE_NAME'] %>
    max_sidekiq_usage: <%= ENV['SETTING_APP_MAX_SIDEKIQ_USAGE'] %>
    asset_host: <%= ENV['SETTING_APP_ASSET_HOST'] %>

  exportable_file:
    max_cells: <%= ENV['SETTING_EXPORTABLE_FILE_MAX_CELLS'] %>
    expired_minutes: <%= ENV['SETTING_EXPORTABLE_FILE_EXPIRED_MINUTES'] %>

  amap:
    js_key: <%= ENV['SETTING_AMAP_JS_KEY'] %>
    web_key: <%= ENV['SETTING_AMAP_WEB_KEY'] %>

  aliyun:
    access_key_id: <%= ENV['SETTING_ALIYUN_ACCESS_KEY_ID'] %>
    access_key_secret: <%= ENV['SETTING_ALIYUN_ACCESS_KEY_ID'] %>
    called_show_number: <%= ENV['SETTING_ALIYUN_CALLED_SHOW_NUMBER'] %>
    tts_codes:
      message: <%= ENV['SETTING_ALIYUN_TTS_CODES_MESSAGE'] %>
      comment: <%= ENV['SETTING_ALIYUN_TTS_CODES_COMMENT'] %>
      organization_application: <%= ENV['SETTING_ALIYUN_TTS_CODES_ORGANIZATION_APPLICATION'] %>
      response_created: <%= ENV['SETTING_ALIYUN_TTS_CODES_RESPONSE_CREATED'] %>
      response_updated: <%= ENV['SETTING_ALIYUN_TTS_CODES_RESPONSE_UPDATED'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
